---
# defaults file for server-nginx
nginx_service: nginx
nginx_user: nginx
nginx_ssl_dhparam_enable: true
nginx_ssl_dhparam_size: 4096
nginx_config_dir: /etc/nginx
nginx_brotli_enabled: true

acme_enabled: true
acme_config_base_path: /root/.config/acme
