---
- name: Read acme base domain
  command: cat {{ acme_config_base_path }}/base-alias-domain.txt
  register: base_alias_domain_file
  changed_when: false

- name: Setup acme facts {{ cert_name }}
  set_fact:
    acme_base_alias_domain: "{{ base_alias_domain_file.stdout | trim }}"
    key_value: "" # necessary for the vscode-ansible checker

- name: Issue certificate {{ cert_name }}
  shell:
    cmd: |
      {{ acme_path }} --issue \
        --dns {{ acme_dns_provider }} \
        {{ cert_domains[:1] | map('quote') | map('regex_replace', '^', '-d ') | join(' ') }} \
        --domain-alias {{ acme_alias_subdomain | default(cert_name) }}.{{ acme_base_alias_domain }} \
        {{ cert_domains[1:] | map('quote') | map('regex_replace', '^', '-d ') | join(' ') }} \
        {{ '--staging' if tlsi.acme.env == 'staging' }} \
        {{ '--force' if tlsi.acme.force }}
  when: source_cert_file_exists == false or tlsi.acme.force
  register: cert_issue_result

- name: Install certificate {{ cert_name }}
  command:
    cmd: >
      {{ acme_path }} --install-cert
      {{ cert_domains | map('quote') | map('regex_replace', '^', '-d ') | join(' ') }}
      --key-file {{ key_file_path }}
      --fullchain-file {{ cert_file_path }}
      {{ '--reloadcmd "' ~ reload_cmd ~ '"' if reload_cmd }}
  when: cert_issue_result.changed
