---
- name: Create cert file {{ cert_name }}
  copy:
    dest: "{{ cert_file_path }}"
    content: "{{ tlsi.cert }}"
- name: Create key file {{ cert_name }}
  copy:
    dest: "{{ key_file_path }}"
    content: "{{ tlsi.key }}"
