---
- name: Issue certificate {{ cert_name }}
  command:
    cmd: >
      {{ acme_path }} --issue
      {{ cert_domains | map('quote') | map('regex_replace', '^', '-d ') | join(' ') }}
      --stateless
      {{ '--staging' if tlsi.acme.env == 'staging' }}
      {{ '--force' if tlsi.acme.force }}
  when: not source_cert_file.stat.exists or tlsi.acme.force
  register: cert_issue_result

- name: Install certificate {{ cert_name }}
  command:
    cmd: >
      {{ acme_path }} --install-cert
      {{ cert_domains | map('quote') | map('regex_replace', '^', '-d ') | join(' ') }}
      --key-file {{ key_file_path }}
      --fullchain-file {{ cert_file_path }}
      {{ '--reloadcmd "' ~ reload_cmd ~ '"' if reload_cmd }}
  when: cert_issue_result.changed
