---
# tasks file for server_acmesh
- name: Install acme.sh
  include_tasks: install.yml

- name: Register acme accounts
  include_tasks: register.yml
  loop:
    - production
    - staging
  loop_control:
    loop_var: env

- name: Store aws credentials for route53
  blockinfile:
    path: "{{ acme_home }}/account.conf"
    marker: "#{mark} ansible acme aws configuration"
    state: present
    block: |
      SAVED_AWS_ACCESS_KEY_ID="{{ acme_aws_access_key_id }}"
      SAVED_AWS_SECRET_ACCESS_KEY="{{ acme_aws_secret_access_key }}"

- name: Store dns credentials
  blockinfile:
    path: "{{ acme_home }}/account.conf"
    marker: "#{mark} ansible acme dns configuration"
    state: present
    block: "{{ lookup('template', 'dns_creds.j2') }}"

- name: Store base alias domain
  copy:
    dest: "{{ acme_config_base_path }}/base-alias-domain.txt"
    content: >
      {{ acme_base_alias_domain }}

- name: Log configuration
  blockinfile:
    path: "{{ acme_home }}/account.conf"
    marker: "#{mark} ansible acme logging configuration"
    state: present
    block: |
      LOG_FILE="{{ acme_home }}/acme.sh.log"
      LOG_LEVEL=1
