---
sshd_config: /etc/ssh/sshd_config
sshd_service: ssh
timezone: Europe/Berlin
bashrc_config: /etc/bash.bashrc
unattended_origins_patterns:
  - 'origin=Ubuntu,archive=${distro_codename}-security'
  - 'o=Ubuntu,a=${distro_codename}'
  - 'o=Ubuntu,a=${distro_codename}-updates'
unattended_email: root
