---
sshd_config: /etc/ssh/sshd_config
sshd_service: ssh
sshd_kexalgorithms:
  - curve25519-sha256@libssh.org
  - curve25519-sha256
  - diffie-hellman-group-exchange-sha256
  - diffie-hellman-group14-sha256
  - diffie-hellman-group16-sha512
  - diffie-hellman-group18-sha512
sshd_ciphers:
  - chacha20-poly1305@openssh.com
  - aes256-gcm@openssh.com
  - aes128-gcm@openssh.com
  - aes256-ctr
  - aes192-ctr
  - aes128-ctr
sshd_macs:
  - hmac-sha2-512-etm@openssh.com
  - hmac-sha2-256-etm@openssh.com
  - umac-128-etm@openssh.com
sshd_hostkeyalgorithms:
  - rsa-sha2-512
  - rsa-sha2-256
  - ssh-ed25519
  - sk-ssh-ed25519@openssh.com

timezone: Europe/Berlin
bashrc_config: /etc/bash.bashrc
unattended_origins_patterns:
  - 'origin=Ubuntu,archive=${distro_codename}-security'
  - 'o=Ubuntu,a=${distro_codename}'
  - 'o=Ubuntu,a=${distro_codename}-updates'
unattended_email: root
packages: []
