---
# tasks file for app-redis
- name: Add redis configuration
  template:
    src: redis.conf.j2
    dest: /home/{{ username }}/{{ config_filename }}
    owner: "{{ username }}"
    group: "{{ username }}"
  notify:
    - restart redis

- name: Setup redis systemd service
  include_role:
    name: peaceman.shared_hosting.app_system
    tasks_from: systemd_unit.yml
  vars:
    unit:
      name: redis
      template: redis.service.j2
      type: service
