---
roles:
  - src: jnv.unattended-upgrades
    version: v1.8.0
  - src: geerlingguy.mysql
    version: 3.1.0
  - src: weareinteractive.ufw
    version: 1.10.0

collections:
  - name: peaceman.shared_hosting
