---
# tasks file for system_redis
- name: Install redis
  apt:
    state: latest
    name: redis

- name: Disable redis system service
  systemd:
    name: "{{ redis_service }}.service"
    enabled: no
    state: stopped
  when: not redis_enable_system_service

- name: Enable redis system service
  systemd:
    name: "{{ redis_server }}.service"
    enabled: yes
    state: started
  when: redis_enable_system_service
