---
# tasks file for app-system
- name: Create system group {{ username }}
  group:
    name: "{{ username }}"
    state: present

- name: Create system user {{ username }}
  user:
    name: "{{ username }}"
    home: /home/{{ username }}
    group: "{{ username }}"
    shell: /bin/bash
    state: present

- name: Add nginx user to the app users group {{ username }}
  user:
    name: "{{ nginx_user }}"
    groups:
      - "{{ username }}"
    append: yes

- name: Ensure home folder permissions /home/{{ username }}
  file:
    path: /home/{{ username }}
    state: directory
    mode: "0750"

- name: Determine systemd service lingering state {{ username }}
  command:
    cmd: loginctl show-user --property=Linger {{ username }}
  register: linger_state
  changed_when: false
  ignore_errors: true # fails if the user is not logged in or lingering

- name: Enable systemd service lingering {{ username }}
  command: loginctl enable-linger {{ username }}
  when: linger_state.stdout != 'Linger=yes'

- name: Ensure existing user sub folders
  file:
    path: /home/{{ username }}/{{ item }}
    state: directory
    recurse: true
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - .config/systemd/user
    - .local/bin

- name: Create mysql config for {{ username }}
  template:
    owner: "{{ username }}"
    group: "{{ username }}"
    src: my.cnf.j2
    dest: /home/{{ username }}/.my.cnf
  vars:
    user: "{{ mysql_username }}"
    password: "{{ mysql_password }}"
    host: "{{ mysql_host }}"
  when: mysql_username | length

- name: Create logs folder for {{ username }}
  file:
    path: /home/{{ username }}/logs
    state: directory
