- name: Copy scripts to the users .local/bin folder
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/{{ username }}/.local/bin/{{ item }}
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  loop:
    - export-to-transfer-folder
    - import-from-transfer-folder
