---
- name: Setup cert facts
  include_tasks: certificate_facts.yml

- name: Check if cert {{ vhost.name }} already exists
  stat:
    path: "{{ cert_file_path }}"
  register: cert_file

- name: Generate self signed cert with name {{ vhost.name }}
  when: not cert_file.stat.exists
  block:
    - name: Generate private key file for {{ vhost.name }}
      openssl_privatekey:
        path: "{{ key_file_path }}"
        cipher: aes256
        passphrase:
    - name: Generate CSR file for {{ vhost.name }}
      openssl_csr:
        path: "{{ csr_file_path }}"
        privatekey_path: "{{ key_file_path }}"
        state: present
        subject_alt_name: "{{ cert_domains | map('regex_replace', '^', 'DNS:') | list }}"
    - name: Sign CSR file for {{ vhost.name }} to create a certificate
      openssl_certificate:
        path: "{{ cert_file_path }}"
        privatekey_path: "{{ key_file_path }}"
        csr_path: "{{ csr_file_path }}"
        provider: selfsigned
