---
- name: Issue certificate {{ vhost.name }}
  shell:
    cmd: |
      {{ acme_path }} --issue \
        --dns dns_aws \
        {{ cert_domains[:1] | map('quote') | map('regex_replace', '^', '-d ') | join(' ') }} \
        --domain-alias {{ vhost.name }}.{{ acme_base_alias_domain }} \
        {{ cert_domains[1:] | map('quote') | map('regex_replace', '^', '-d ') | join(' ') }} \
        {{ '--staging' if vhost.tls.acme.env == 'staging' }} \
        {{ '--force' if vhost.tls.acme.force }}
  when: not source_cert_file.stat.exists or vhost.tls.acme.force
  register: cert_issue_result

- name: Install certificate {{ vhost.name }}
  command:
    cmd: >
      {{ acme_path }} --install-cert
      {{ cert_domains | map('quote') | map('regex_replace', '^', '-d ') | join(' ') }}
      --key-file {{ key_file_path }}
      --fullchain-file {{ cert_file_path }}
      --reloadcmd "systemctl reload {{ nginx_service }}.service"
  when: cert_issue_result.changed
