---
# tasks file for app-nginx
- name: Setup varnish purge frontend hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ username }}-varnish-purge$'
    line: "{{ nginx_varnish_purge_frontend_ip }} {{ username }}-varnish-purge"
    state: present
  when: varnish_enabled

- name: Generate basic auth htpasswd files
  include_tasks: basic_auth.yml

- include_tasks: vhost.yml
  vars:
    vhosts: "{{ vhosts_defaulted }}"
    document_root_full: "/home/{{ [username, 'app', document_root] | select() | join('/') }}"
    vhost_filename: "{{ username }}"

- name: Generate certificate
  include_tasks: certificate.yml
  loop: "{{ vhosts_defaulted }}"
  loop_control:
    loop_var: vhost

- name: Ensure app folder exists
  file:
    state: directory
    path: /home/{{ username }}/app
    owner: "{{ username }}"
    group: "{{ username }}"
