---
- name: Update apt
  apt:
    update_cache: yes

- name: Set system hostname
  hostname:
    name: "{{ hostname | default(inventory_hostname, true) }}"

- name: Update locale to en_US.utf-8
  command:
    cmd: update-locale LANG=en_US.utf-8

- name: Update timezone
  command:
    cmd: timedatectl set-timezone {{ timezone }}

- name: Configure permanent bash history with date and time
  blockinfile:
    marker: "#{mark} ansible permanent bash history"
    state: present
    content: "{{ lookup('file', 'files/permanent-bash-history') }}"
    path: "{{ bashrc_config }}"

- name: Global vim configuration
  copy:
    src: vimrc.local
    dest: /etc/vim/vimrc.local

- name: Provide XDG_RUNTIME_DIR for systemd user services
  copy:
    src: xdg-runtime.sh
    dest: /etc/profile.d/xdg-runtime.sh
    mode: 0755

- name: Configure sshd
  include_tasks: sshd.yml

- name: Install common packages
  include_tasks: packages.yml

- name: Configure firewall
  include_tasks: ufw.yml

- name: Configure mail aliases
  lineinfile:
    path: /etc/aliases
    regexp: "root: "
    line: "root: {{ mail_aliases_root | mandatory }}"
    state: present
  notify: rebuild aliases

- name: Setup authorized ssh keys for root
  authorized_key:
    comment: "{{ item.comment | default(omit) }}"
    key: "{{ item.key }}"
    state: "{{ item.state | default(omit) }}"
    user: root
  loop: "{{ ssh_keys_root }}"

- name: Configure global bash aliases
  template:
    src: "bash-aliases.sh.j2"
    dest: "/etc/profile.d/bash-aliases.sh"
    validate: bash -n %s

- name: Configure logrotate for user logs
  include_tasks: logrotate.yml
