---
- name: Disable password authentication
  lineinfile:
    path: "{{ sshd_config }}"
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart sshd

- name: Enable PAM
  lineinfile:
    path: "{{ sshd_config }}"
    regexp: "^#?UsePAM"
    line: "UsePAM yes"
    state: present
  notify: restart sshd
