---
# tasks file for app-mysql
- name: Create mysql user
  mysql_user:
    name: "{{ username }}"
    password: "{{ password }}"
    priv: "{{ item }}.*:ALL"
    host: "%"
    state: present
  loop: "{{ databases }}"

- name: Create mysql databases
  mysql_db:
    name: "{{ databases }}"
    state: present
