---
# tasks file for app-mysql
- name: Create mysql user
  mysql_user:
    name: "{{ username }}"
    password: "{{ password }}"
    priv: >-
      {{
        (
          databases | map('regex_replace', '$', '.*:ALL')
          + [
            '*.*:' + ([
              'SESSION_VARIABLES_ADMIN' if mysql_version is version('8.0', '>=') else '',
              'RELOAD',
            ] | select() | join(','))
          ]
        ) | select() | join('/')
      }}
    host: "%"
    state: present

- name: Create mysql databases
  mysql_db:
    name: "{{ databases }}"
    state: present
