---
# tasks file for app-mysql
- name: Create mysql user
  mysql_user:
    name: "{{ username }}"
    password: "{{ password }}"
    priv: >-
      {{ [
        item + '.*:ALL',
        '*.*:SESSION_VARIABLES_ADMIN' if mysql_version is version('8.0', '>=') else '',
        ] | select() | join('/')
      }}
    host: "%"
    state: present
  loop: "{{ databases }}"

- name: Create mysql databases
  mysql_db:
    name: "{{ databases }}"
    state: present
