---
# tasks file for app_php
- name: Determine installed php versions
  command:
    cmd: find /etc/php -mindepth 1 -maxdepth 1 -type d -printf '%P\n'
  register: found_php_versions

- name: Remove php fpm pool file for {{ username }}
  include_tasks: remove_fpm_pool_file.yml
  loop: "{{ found_php_versions.stdout_lines }}"
  loop_control:
    loop_var: php_version

- name: Configure php fpm pool for {{ username }}
  template:
    src: pool.conf.j2
    dest: /etc/php/{{ php_version }}/fpm/pool.d/{{ username }}.conf
  vars:
    directives: "{{ fpm_directives }}"

- name: Reload php{{ php_version }}-fpm
  systemd:
    name: php{{ php_version }}-fpm.service
    state: reloaded

- name: Determine full path ot php {{ php_version }} binary
  command:
    cmd: which php{{ php_version }}
  register: php_binary
  changed_when: false

- name: Link used php {{ php_version }} binary into user path
  file:
    dest: /home/{{ username }}/.local/bin/php
    src: "{{ php_binary.stdout }}"
    state: link
