---
- name: Remove php fpm pool file {{ version }} for {{ username }}
  file:
    path: /etc/php/{{ version }}/fpm/pool.d/{{ username }}.conf
    state: absent
  register: remove_pool_file

- name: Reload php{{ version }}-fpm
  systemd:
    name: php{{ version }}-fpm.service
    state: reloaded
  when: remove_pool_file.changed
