---
# defaults file for app-nginx
redirect_status_code: 301
document_root: # relative to the app folder
index_file: index.php
autoindex: "off"
charset: UTF-8
template: php-generic.conf.j2
configuration: []
varnish_configuration: []

# varnish specifics
varnish_enabled: false
nginx_varnish_backend_ip: 127.0.0.23
nginx_varnish_backend_port: 80
nginx_varnish_purge_frontend_ip: 127.0.0.22
nginx_varnish_purge_frontend_port: 80

nginx_user: nginx
nginx_service: nginx
nginx_config_dir: /etc/nginx
nginx_brotli_enabled: true
acme_enabled: true
acme_config_base_path: /root/.config/acme

# used in shopware5.conf.j2 template
sw5_treat_html_as_static: true
