---
# tasks file for server_mysql
- name: Install official mysql repo
  include_tasks: repo.yml

- name: Install mysql
  import_role:
    name: geerlingguy.mysql

- name: Ensure there is a debian.cnf for other programs to use
  template:
    src: debian.cnf.j2
    dest: /etc/mysql/debian.cnf
    mode: 0600
    owner: root
    group: root

- name: Setup mysql backup
  include_tasks: automysqlbackup.yml

- name: Configure firewall for mysql
  include_tasks: ufw.yml
