---
# tasks file for server_mysql
- name: Install mysql
  import_role:
    name: geerlingguy.mysql

- name: Setup mysql backup
  include_tasks: automysqlbackup.yml

- name: Configure firewall for mysql
  include_tasks: ufw.yml
